//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnsurancePolicyEntities : DbContext
    {
        public EnsurancePolicyEntities()
            : base("name=EnsurancePolicyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<CoverageKind> CoverageKind { get; set; }
        public virtual DbSet<Policy> Policy { get; set; }
        public virtual DbSet<RiskKind> RiskKind { get; set; }
        public virtual DbSet<ClientPolicy> ClientPolicy { get; set; }
    }
}
