//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policy()
        {
            this.ClientPolicy = new HashSet<ClientPolicy>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short Coverage { get; set; }
        public int CoverageKindId { get; set; }
        public long Prize { get; set; }
        public short Period { get; set; }
        public int RiskKind { get; set; }
        public string Description { get; set; }
    
        public virtual CoverageKind CoverageKind { get; set; }
        public virtual RiskKind RiskKind1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPolicy> ClientPolicy { get; set; }
    }
}
